/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as MemberRouteRouteImport } from './routes/member/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MemberIndexRouteImport } from './routes/member/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as MemberProfileRouteImport } from './routes/member/profile'
import { Route as MemberPaymentsRouteImport } from './routes/member/payments'
import { Route as MemberLoginRouteImport } from './routes/member/login'
import { Route as MemberDependantsRouteImport } from './routes/member/dependants'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminPaymentsIndexRouteImport } from './routes/admin/payments/index'
import { Route as AdminMembersIndexRouteImport } from './routes/admin/members/index'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api/webhooks/stripe'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminPaymentsNewRouteImport } from './routes/admin/payments/new'
import { Route as AdminMembersNewRouteImport } from './routes/admin/members/new'
import { Route as AdminMembersIdRouteImport } from './routes/admin/members/$id'

const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberRouteRoute = MemberRouteRouteImport.update({
  id: '/member',
  path: '/member',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberIndexRoute = MemberIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MemberRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const MemberProfileRoute = MemberProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MemberRouteRoute,
} as any)
const MemberPaymentsRoute = MemberPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => MemberRouteRoute,
} as any)
const MemberLoginRoute = MemberLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => MemberRouteRoute,
} as any)
const MemberDependantsRoute = MemberDependantsRouteImport.update({
  id: '/dependants',
  path: '/dependants',
  getParentRoute: () => MemberRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPaymentsIndexRoute = AdminPaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMembersIndexRoute = AdminMembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsNewRoute = AdminPaymentsNewRouteImport.update({
  id: '/payments/new',
  path: '/payments/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMembersNewRoute = AdminMembersNewRouteImport.update({
  id: '/members/new',
  path: '/members/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMembersIdRoute = AdminMembersIdRouteImport.update({
  id: '/members/$id',
  path: '/members/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/member': typeof MemberRouteRouteWithChildren
  '/donate': typeof DonateRoute
  '/admin/login': typeof AdminLoginRoute
  '/member/dependants': typeof MemberDependantsRoute
  '/member/login': typeof MemberLoginRoute
  '/member/payments': typeof MemberPaymentsRoute
  '/member/profile': typeof MemberProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/member/': typeof MemberIndexRoute
  '/admin/members/$id': typeof AdminMembersIdRoute
  '/admin/members/new': typeof AdminMembersNewRoute
  '/admin/payments/new': typeof AdminPaymentsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/admin/members/': typeof AdminMembersIndexRoute
  '/admin/payments/': typeof AdminPaymentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/donate': typeof DonateRoute
  '/admin/login': typeof AdminLoginRoute
  '/member/dependants': typeof MemberDependantsRoute
  '/member/login': typeof MemberLoginRoute
  '/member/payments': typeof MemberPaymentsRoute
  '/member/profile': typeof MemberProfileRoute
  '/admin': typeof AdminIndexRoute
  '/member': typeof MemberIndexRoute
  '/admin/members/$id': typeof AdminMembersIdRoute
  '/admin/members/new': typeof AdminMembersNewRoute
  '/admin/payments/new': typeof AdminPaymentsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/admin/members': typeof AdminMembersIndexRoute
  '/admin/payments': typeof AdminPaymentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/member': typeof MemberRouteRouteWithChildren
  '/donate': typeof DonateRoute
  '/admin/login': typeof AdminLoginRoute
  '/member/dependants': typeof MemberDependantsRoute
  '/member/login': typeof MemberLoginRoute
  '/member/payments': typeof MemberPaymentsRoute
  '/member/profile': typeof MemberProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/member/': typeof MemberIndexRoute
  '/admin/members/$id': typeof AdminMembersIdRoute
  '/admin/members/new': typeof AdminMembersNewRoute
  '/admin/payments/new': typeof AdminPaymentsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/admin/members/': typeof AdminMembersIndexRoute
  '/admin/payments/': typeof AdminPaymentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/member'
    | '/donate'
    | '/admin/login'
    | '/member/dependants'
    | '/member/login'
    | '/member/payments'
    | '/member/profile'
    | '/admin/'
    | '/member/'
    | '/admin/members/$id'
    | '/admin/members/new'
    | '/admin/payments/new'
    | '/api/auth/$'
    | '/api/webhooks/stripe'
    | '/admin/members/'
    | '/admin/payments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/donate'
    | '/admin/login'
    | '/member/dependants'
    | '/member/login'
    | '/member/payments'
    | '/member/profile'
    | '/admin'
    | '/member'
    | '/admin/members/$id'
    | '/admin/members/new'
    | '/admin/payments/new'
    | '/api/auth/$'
    | '/api/webhooks/stripe'
    | '/admin/members'
    | '/admin/payments'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/member'
    | '/donate'
    | '/admin/login'
    | '/member/dependants'
    | '/member/login'
    | '/member/payments'
    | '/member/profile'
    | '/admin/'
    | '/member/'
    | '/admin/members/$id'
    | '/admin/members/new'
    | '/admin/payments/new'
    | '/api/auth/$'
    | '/api/webhooks/stripe'
    | '/admin/members/'
    | '/admin/payments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  MemberRouteRoute: typeof MemberRouteRouteWithChildren
  DonateRoute: typeof DonateRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member': {
      id: '/member'
      path: '/member'
      fullPath: '/member'
      preLoaderRoute: typeof MemberRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member/': {
      id: '/member/'
      path: '/'
      fullPath: '/member/'
      preLoaderRoute: typeof MemberIndexRouteImport
      parentRoute: typeof MemberRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/member/profile': {
      id: '/member/profile'
      path: '/profile'
      fullPath: '/member/profile'
      preLoaderRoute: typeof MemberProfileRouteImport
      parentRoute: typeof MemberRouteRoute
    }
    '/member/payments': {
      id: '/member/payments'
      path: '/payments'
      fullPath: '/member/payments'
      preLoaderRoute: typeof MemberPaymentsRouteImport
      parentRoute: typeof MemberRouteRoute
    }
    '/member/login': {
      id: '/member/login'
      path: '/login'
      fullPath: '/member/login'
      preLoaderRoute: typeof MemberLoginRouteImport
      parentRoute: typeof MemberRouteRoute
    }
    '/member/dependants': {
      id: '/member/dependants'
      path: '/dependants'
      fullPath: '/member/dependants'
      preLoaderRoute: typeof MemberDependantsRouteImport
      parentRoute: typeof MemberRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/payments/': {
      id: '/admin/payments/'
      path: '/payments'
      fullPath: '/admin/payments/'
      preLoaderRoute: typeof AdminPaymentsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/members/': {
      id: '/admin/members/'
      path: '/members'
      fullPath: '/admin/members/'
      preLoaderRoute: typeof AdminMembersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments/new': {
      id: '/admin/payments/new'
      path: '/payments/new'
      fullPath: '/admin/payments/new'
      preLoaderRoute: typeof AdminPaymentsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/members/new': {
      id: '/admin/members/new'
      path: '/members/new'
      fullPath: '/admin/members/new'
      preLoaderRoute: typeof AdminMembersNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/members/$id': {
      id: '/admin/members/$id'
      path: '/members/$id'
      fullPath: '/admin/members/$id'
      preLoaderRoute: typeof AdminMembersIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminMembersIdRoute: typeof AdminMembersIdRoute
  AdminMembersNewRoute: typeof AdminMembersNewRoute
  AdminPaymentsNewRoute: typeof AdminPaymentsNewRoute
  AdminMembersIndexRoute: typeof AdminMembersIndexRoute
  AdminPaymentsIndexRoute: typeof AdminPaymentsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminMembersIdRoute: AdminMembersIdRoute,
  AdminMembersNewRoute: AdminMembersNewRoute,
  AdminPaymentsNewRoute: AdminPaymentsNewRoute,
  AdminMembersIndexRoute: AdminMembersIndexRoute,
  AdminPaymentsIndexRoute: AdminPaymentsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface MemberRouteRouteChildren {
  MemberDependantsRoute: typeof MemberDependantsRoute
  MemberLoginRoute: typeof MemberLoginRoute
  MemberPaymentsRoute: typeof MemberPaymentsRoute
  MemberProfileRoute: typeof MemberProfileRoute
  MemberIndexRoute: typeof MemberIndexRoute
}

const MemberRouteRouteChildren: MemberRouteRouteChildren = {
  MemberDependantsRoute: MemberDependantsRoute,
  MemberLoginRoute: MemberLoginRoute,
  MemberPaymentsRoute: MemberPaymentsRoute,
  MemberProfileRoute: MemberProfileRoute,
  MemberIndexRoute: MemberIndexRoute,
}

const MemberRouteRouteWithChildren = MemberRouteRoute._addFileChildren(
  MemberRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  MemberRouteRoute: MemberRouteRouteWithChildren,
  DonateRoute: DonateRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
